export enum ErrorCode{
    UNAUTHORIZED = "UNAUTHORIZED",
    VALIDATION_ERROR = "VALIDATION_ERROR",
    UNKNOWN_ERROR = "UNKNOWN_ERROR",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    FORBIDDEN= "INSUFFICIENT_PERMISSIONS",
    INTERNAL_ERROR= "INTERNAL_SERVER_ERROR",
    NOT_FOUND = "NOT_FOUND",
    BAD_REQUEST = "BAD_REQUEST",
    DATABASE_ERROR="DATABASE_ERROR",
    PAYMENT_ERROR="PAYMENT_ERROR"
}